const EDUCATION = [
  { key: "Agricultural Sciences", value: "Agricultural Sciences" },
  { key: "Architecture", value: "Architecture" },
  { key: "B.E", value: "B.E" },
  { key: "B.Com", value: "B.Com" },
  { key: "B.Ed", value: "B.Ed" },
  { key: "B.Sc", value: "B.Sc" },
  { key: "B.Tech", value: "B.Tech" },
  { key: "BA", value: "BA" },
  { key: "Bachelor in Optometry", value: "Bachelor in Optometry" },
  { key: "Bachelor in Psychology", value: "Bachelor in Psychology" },
  {
    key: "Bachelor of Ayurvedic Medicine and Surgery - BAMS",
    value: "Bachelor of Ayurvedic Medicine and Surgery - BAMS",
  },
  {
    key: "Bachelor of Fire Engineering",
    value: "Bachelor of Fire Engineering",
  },
  {
    key: "Bachelor of Homoeopathic Medicine and Surgery (BHMS)",
    value: "Bachelor of Homoeopathic Medicine and Surgery (BHMS)",
  },
  { key: "Bachelor of Law", value: "Bachelor of Law" },
  { key: "BCA", value: "BCA" },
  { key: "BSW", value: "BSW" },
  { key: "CA", value: "CA" },
  { key: "CAIIB", value: "CAIIB" },
  {
    key: "Chemical/Refinery and Petrochemical Engineering",
    value: "Chemical/Refinery and Petrochemical Engineering",
  },
  { key: "Computer Programming", value: "Computer Programming" },
  {
    key: "Degree in Aeronautical Engineering",
    value: "Degree in Aeronautical Engineering",
  },
  { key: "Degree in Biotechnology", value: "Degree in Biotechnology" },
  { key: "Degree in Chemistry", value: "Degree in Chemistry" },
  { key: "Degree in Fishery Science", value: "Degree in Fishery Science" },
  { key: "Degree in Guitar", value: "Degree in Guitar" },
  { key: "Degree in Harmonium", value: "Degree in Harmonium" },
  { key: "Degree in Home Science", value: "Degree in Home Science" },
  { key: "Degree in Library Science", value: "Degree in Library Science" },
  { key: "Degree in Mandolin", value: "Degree in Mandolin" },
  { key: "Degree in Nutrition", value: "Degree in Nutrition" },
  { key: "Degree in Physiotherapy", value: "Degree in Physiotherapy" },
  { key: "Degree in Synthesizer", value: "Degree in Synthesizer" },
  { key: "Dental Studies", value: "Dental Studies" },
  { key: "Diploma in Agriculture", value: "Diploma in Agriculture" },
  { key: "Diploma in Catering", value: "Diploma in Catering" },
  {
    key: "Diploma in Civil Engineering",
    value: "Diploma in Civil Engineering",
  },
  { key: "Diploma in Conservation", value: "Diploma in Conservation" },
  {
    key: "Diploma in Electrical Communication",
    value: "Diploma in Electrical Communication",
  },
  { key: "Diploma in Engineering", value: "Diploma in Engineering" },
  {
    key: "Diploma in Film and Video Editing",
    value: "Diploma in Film and Video Editing",
  },
  {
    key: "Diploma in Finance and Accounts",
    value: "Diploma in Finance and Accounts",
  },
  {
    key: "Diploma in Mechanical or Electrical Engineering",
    value: "Diploma in Mechanical or Electrical Engineering",
  },
  { key: "Diploma in Nursing", value: "Diploma in Nursing" },
  { key: "Diploma in Surveying", value: "Diploma in Surveying" },
  {
    key: "Diploma in Telecommunication",
    value: "Diploma in Telecommunication",
  },
  {
    key: "Diploma in Thermal Power Plant Engineering",
    value: "Diploma in Thermal Power Plant Engineering",
  },
  {
    key: "Diploma in TV/Radio Production",
    value: "Diploma in TV/Radio Production",
  },
  { key: "DM", value: "DM" },
  { key: "DNB", value: "DNB" },
  { key: "Electrical Engineering", value: "Electrical Engineering" },
  { key: "Graduate", value: "Graduate" },
  { key: "Hindi", value: "Hindi" },
  { key: "ICAI", value: "ICAI" },
  { key: "ICWA", value: "ICWA" },
  { key: "ITI", value: "ITI" },
  { key: "LLB", value: "LLB" },
  {
    key: "M. Phil in Physical Education",
    value: "M. Phil in Physical Education",
  },
  { key: "M.B.B.S", value: "M.B.B.S" },
  { key: "M.Ch", value: "M.Ch" },
  { key: "M.Com", value: "M.Com" },
  { key: "M.E.", value: "M.E." },
  { key: "M.Phil", value: "M.Phil" },
  { key: "M.Sc", value: "M.Sc" },
  { key: "M.Tech", value: "M.Tech" },
  { key: "M.Tech in Computer Science", value: "M.Tech in Computer Science" },
  { key: "MA", value: "MA" },
  {
    key: "MCM [Master in Computer Management]",
    value: "MCM [Master in Computer Management]",
  },
  { key: "Masters Degree in Education", value: "Masters Degree in Education" },
  { key: "Masters Degree in English", value: "Masters Degree in English" },
  {
    key: "Masters Degree in Humanities",
    value: "Masters Degree in Humanities",
  },
  { key: "Masters Degree in Physics", value: "Masters Degree in Physics" },
  { key: "MBA", value: "MBA" },
  { key: "MCA", value: "MCA" },
  { key: "MD", value: "MD" },
  { key: "Mechanical Engineering", value: "Mechanical Engineering" },
  { key: "MS", value: "MS" },
  { key: "MSW", value: "MSW" },
  {
    key: "Petroleum/Petrochemical Engineering",
    value: "Petroleum/Petrochemical Engineering",
  },
  { key: "PG Diploma", value: "PG Diploma" },
  {
    key: "PG Diploma in Personnel Management",
    value: "PG Diploma in Personnel Management",
  },
  {
    key: "PG Diploma in Rural Services",
    value: "PG Diploma in Rural Services",
  },
  { key: "PG in Political Science", value: "PG in Political Science" },
  { key: "PGDCA", value: "PGDCA" },
  { key: "Ph.D", value: "Ph.D" },
  {
    key: "Post Graduate Diploma in Operations Management",
    value: "Post Graduate Diploma in Operations Management",
  },
  {
    key: "Post Graduate Diploma in Technology",
    value: "Post Graduate Diploma in Technology",
  },
  { key: "Post-Graduate", value: "Post-Graduate" },
  { key: "RDSO competency certificate", value: "RDSO competency certificate" },
  { key: "Teacher Eligibility Test", value: "Teacher Eligibility Test" },
  { key: "Urdu", value: "Urdu" },
];

const BACHELORS = [
  "Bachelor of Architecture (BArch)",
  "Bachelor of Design (BDes)",
  "Bachelor of Arts (BA)",
  "Bachelor of Applied Arts (BAA)",
  "Bachelor of Applied Arts and Science (BAAS)",
  "Bachelor of Engineering (BE)",
  "Bachelor of Engineering Technology (BSET)",
  "Bachelor of Business Administration (BBA)",
  "International Business Economics (BIBE)",
  "Bachelor of Science in Business (BSBA)",
  "Bachelor of Management Studies (BMS)",
  "Bachelor of Administrative Studies",
  "Bachelor of International Business Economics (BIBE)",
  "Bachelor of Commerce (BCom)",
  "Bachelor of Business (BBus)",
  "Bachelor of Management and Organizational Studies (BMOS)",
  "Bachelor of Business Science (BBusSc)",
  "Bachelor of Accountancy (B.Acc)",
  "Bachelor of Comptrolling (B.Compt)",
  "Bachelor of Economics (BEc)",
  "Bachelor of Arts in Organizational Management (BAOM)",
  "Bachelor of Computing (BComp)",
  "Bachelor of Computer Science (BCompSc)",
  "Bachelor of Science in Information Technology (BSc IT)",
  "Bachelor of Computer Applications (BCA)",
  "Bachelor of Applied Science in Information Technology (BAppSc IT)",
  "Bachelor of Business Information Systems (BBIS)",
  "Intercalated Bachelor of Science (BSc)",
  "Bachelor of Medical Science (BMedSci)",
  "Bachelor of Medical Biology (BMedBiol)",
  "Doctorate of Dental Surgery (DDS)",
  "Bachelor of Science in Nursing (BScN)",
  "Bachelor of Science in Public Health (BSPH)",
  "Bachelor of Health Science (BHSc)",
  "Bachelor of Science in Human Biology (BSc)",
  "Bachelor of Kinesiology (BSc Kin)",
  "Bachelor of Aviation (BAvn)",
  "Bachelor of Divinity (BDiv)",
  "Bachelor of Theology (B.Th)",
  "Bachelor of Religious Studies (BRS)",
  "Bachelor of Religious Education (BRE)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Film and Television (BF&TV)",
  "Bachelor of Integrated studies (BIS)",
  "Bachelor of Journalism (BJourn)",
  "Bachelor of Landscape Architecture (BLArch)",
  "Bachelor of Liberal Arts (B.L.A)",
  "Bachelor of General Studies (BSGS)",
  "Bachelor of Applied Studies (BAS)",
  "Bachelor of Liberal Studies",
  "Bachelor of Professional Studies (BPS)",
  "Bachelor of Library Science (B.Lib)",
  "Bachelor of Library and Information Science (B.L.I.S)",
  "Bachelor of Music (BMus)",
  "Bachelor of Art in Music (BA in Music)",
  "Bachelor of Music Education (BME)",
  "Bachelor of Mortuary Science (BMS)",
  "Bachelor of Philosophy (BPhil)",
  "Bachelor of Arts in Psychology (BAPSY)",
  "Bachelor of Science in Psychology (BSc Psych)",
  "Bachelor of Science in Education (BSEd)",
  "Bachelor of Science in Finance",
  "Bachelor of Arts for Teaching (BAT)",
  "Bachelor of Science in Forestry (B.Sc.F)",
  "Bachelor of Applied Science (BASc)",
  "Bachelor of Science in Law (BSL)",
  "Bachelor of Social Science (BSocSc)",
  "Bachelor of Arts in Social Work (BASW)",
  "Bachelor of Technology (B.Tech)",
  "Bachelor of Talmudic Law (BTL)",
  "Bachelor of Tourism Studies (BTS)",
  "Bachelor of Mathematics (BMath)",
  "Bachelor of Mathematical Sciences (BMathSc)",
  "Bachelor of Urban and Regional Planning (BPlan)",
  "Bachelor of Public Affairs and Policy Management (BPAPM)",
];

const MASTERS = [
  "Master of Accountancy (MAcc)",
  "Master of Advanced Study (M.A.S)",
  "Master of Economics (M.Econ)",
  "Master of Applied Science (MASc)",
  "Master of Architecture (M.Arch)",
  "Master of Arts (M.A)",
  "Master of Arts in Teaching (MAT)",
  "Master of Arts in Liberal Studies (MALS)",
  "Master of Business Administration (MBA)",
  "Master of Business (MBus)",
  "Master of Business Informatics (MBI)",
  "Master of Chemistry (MChem)",
  "Master of City Planning",
  "Master of Commerce (MCom)",
  "Master of Computational Finance",
  "Master of Computer Applications (MCA)",
  "Master of Criminal Justice (MCJ)",
  "Master in Creative Technologies",
  "Master of Design (MDes)",
  "Master of Divinity (M.Div)",
  "Master of Education (M.Ed)",
  "Master of Engineering (M.Eng)",
  "Master of Engineering Management (MEM)",
  "Master of Enterprise (M.Ent)",
  "Master of European Law (LL.M. Eur)",
  "Master of Finance (M.Fin)",
  "Master of Financial Economics",
  "Master of Financial Engineering",
  "Master of Financial Mathematics",
  "Master of Fine Arts (MFA)",
  "Master of Health Administration (MHA)",
  "Master of Health Science (MHS)",
  "Master of Humanities (MH)",
  "Master of Industrial and Labor Relations (MILR)",
  "Master of International Affairs",
  "Master of International Business",
  "Masters in International Economics",
  "Master of International Studies (MIS)",
  "Master of Information System Management (M.ISM)",
  "Master of IT (M.Sc.IT)",
  "Master of Jurisprudence (M.Jur)",
  "Master of Laws (LLM)",
  "Master of Studies in Law (M.S.L)",
  "Master of Landscape Architecture (M.Arch)",
  "Master of Letters (MLitt)",
  "Master of Liberal Arts (MA)",
  "Master of Library and Information Science (MLIS)",
  "Master of Management (MM)",
  "Master of Mathematical Finance",
  "Master of Mathematics (MMath)",
  "Master of Medical Science",
  "Master of Music (M.Mus)",
  "Master of Occupational Therapy (OT)",
  "Master of Pharmacy (MPharm)",
  "Master of Philosophy (M.Phil)",
  "Master of Physician Assistant Studies",
  "Master of Physics (MPhys)",
  "Master of Political Science",
  "Master of Professional Studies (M.P.S)",
  "Master of Public Administration (MPA)",
  "Master of Public Affairs (M.P.Aff)",
  "Master of Public Health (M.P.H)",
  "Master of Public Policy (M.P.P)",
  "Master of Public Management",
  "Master of Quantitative Finance",
  "Master of Rabbinic Studies (MRb)",
  "Master of Real Estate Development",
  "Master of Religious Education",
  "Master of Research (MSc.R)",
  "Master of Sacred Music (MSM)",
  "Master of Sacred Theology (S.T.M)",
  "Master of Science (MSc)",
  "Master of Science in Education",
  "Master of Science in Engineering (MSE)",
  "Master of Science in Finance (M.Fin)",
  "Master of Science in Human Resource Development (HRD)",
  "Master of Science in Information Systems (MSIS)",
  "Master of Science in Information Systems Management (MSMIS)",
  "Master of Science in Information Technology (MSc.IT)",
  "Master of Science in Leadership (MSL)",
  "Master of Science in Management",
  "Master of Science in Nursing (MSN)",
  "Master of Science in Project Management (M.S.P.M)",
  "Master of Science in Supply Chain Management (SCM)",
  "Master of Science in Teaching (MST)",
  "Master of Science in Taxation",
  "Master of Social Science (MSSc)",
  "Master of Social Work (MSW)",
  "Master of Studies (M.St)",
  "Master of Surgery",
  "Master of Theological Studies (M.T.S)",
  "Master of Theology (M.Th)",
  "Master of Urban Planning",
  "Master of Veterinary Science (MVSc)",
];

const YEAR_OF_PASSING = [
  2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010,
  2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997,
  1996, 1995, 1994, 1993, 1992, 1991, 1990,
];

export { EDUCATION, BACHELORS, MASTERS, YEAR_OF_PASSING };
