export const DUMMY_DATA = [
  {
    _id: "6217ceb6de0c0d1c29c1e615",
    firstName: " tarzan",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\cefeb360-959f-11ec-a4b3-a9874fbce624.pdf",
    __v: 0,
  },
  {
    _id: "6217cf33de09555edd709626",
    firstName: " tarzan",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\199d06b0-95a0-11ec-87ac-c51bdd0d4095.pdf",
    __v: 0,
  },
  {
    _id: "6217cf67ed158df08965dfa5",
    firstName: " tarzan",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\382f9070-95a0-11ec-b7d9-57ca99b29bc8.pdf",
    __v: 0,
  },
  {
    _id: "6217cfaee2d9ca1eaab05a7f",
    firstName: " jackie",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\62c86910-95a0-11ec-897b-f92be96bbf52.pdf",
    __v: 0,
  },
  {
    _id: "6217d08ae2d9ca1eaab05a82",
    firstName: "ironman",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\e59a8da0-95a0-11ec-897b-f92be96bbf52.pdf",
    __v: 0,
  },
  {
    _id: "6217d0b2e2d9ca1eaab05a85",
    firstName: "hulk",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\fdb4e700-95a0-11ec-897b-f92be96bbf52.pdf",
    __v: 0,
  },
  {
    _id: "6217d0d1f4ad65a51253e359",
    firstName: "thor",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\10074d30-95a1-11ec-8c45-dfcfb2c33e4c.pdf",
    __v: 0,
  },
  {
    _id: "6217d11982515fa1479a5d25",
    firstName: "thor",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\3b478960-95a1-11ec-b3e3-09fe4675cae5.pdf",
    __v: 0,
  },
  {
    _id: "6217d13b0a35ed725757f044",
    firstName: "thor",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\4f5b4ea0-95a1-11ec-accf-f7d44b42efe0.pdf",
    __v: 0,
  },
  {
    _id: "6217d19ea2af911ef97e5ea8",
    firstName: "thor",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\8a9e34a0-95a1-11ec-aad5-51bff28aa687.pdf",
    __v: 0,
  },
  {
    _id: "6217d1c2c3e89c8ab3315252",
    firstName: "thor",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\9f935930-95a1-11ec-a8ac-233850b54612.pdf",
    __v: 0,
  },
  {
    _id: "6217d1d4259e6d3419276e88",
    firstName: "thor",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "amalvarghese593@gmail.com",
    secondaryEmailId: "vhjgahgvhj@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\aa799210-95a1-11ec-8631-abeb478c30ac.pdf",
    __v: 0,
  },
  {
    _id: "6217d5196ab909847d0b8726",
    firstName: "thor",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "ghsgah@gmail.com",
    secondaryEmailId: "amalvarghese593@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\9dadbe60-95a3-11ec-aa4f-b9123a686835.pdf",
    __v: 0,
  },
  {
    _id: "6217d8de9142dbcf10ff1ca1",
    firstName: "thor",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 9747716799,
    primaryEmailId: "ghsgasssh@gmail.com",
    secondaryEmailId: "amalvarghsese593@gmail.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\dcd4f890-95a5-11ec-a928-c3d0a7e652e7.pdf",
    __v: 0,
  },
  {
    _id: "621869b96d32631c1d4af997",
    firstName: "thor",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 5694539595,
    primaryEmailId: "sda@g.com",
    secondaryEmailId: "asasd@g.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\3407b3e0-95fc-11ec-a530-09fa7c1a7b35.pdf",
    __v: 0,
  },
  {
    _id: "62186a6e6d32631c1d4af9a0",
    firstName: "thor",
    middleName: " ''\"",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 7994539593,
    primaryEmailId: "sjshjshjhjda@g.com",
    secondaryEmailId: "asassxsxd@g.com",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\9f940d20-95fc-11ec-a530-09fa7c1a7b35.pdf",
    __v: 0,
  },
  {
    _id: "621887b442999d58dfa644e0",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: 7994539593,
    primaryEmailId: "amalvarghghghhese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\12b31ec0-960e-11ec-acdf-d77f50d9c9a4.pdf",
    __v: 0,
  },
  {
    _id: "621887e242999d58dfa644e3",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539523,
    secondaryContactNumber: null,
    primaryEmailId: "amalvaghghhese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\2dce3500-960e-11ec-acdf-d77f50d9c9a4.pdf",
    __v: 0,
  },
  {
    _id: "6218897e9f002bdb2800e886",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539595,
    secondaryContactNumber: null,
    primaryEmailId: "amalvaghghese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\238c5d00-960f-11ec-bb57-1d9d9c7c09a5.pdf",
    __v: 0,
  },
  {
    _id: "62188acb5de9b94875f9c2e2",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 7994539567,
    secondaryContactNumber: 9747716778,
    primaryEmailId: "samalvaghghese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\e9e55740-960f-11ec-a7ee-13ef282cd3f5.pdf",
    __v: 0,
  },
  {
    _id: "62188b3b28b9a25b40f02f2f",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9747716456,
    secondaryContactNumber: null,
    primaryEmailId: "ssamalvaghghese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\2c74d4a0-9610-11ec-a716-39053d3bc565.pdf",
    __v: 0,
  },
  {
    _id: "62189e88d229d3d1ebbc258e",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9747716486,
    secondaryContactNumber: null,
    primaryEmailId: "ssamaslvaghghese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\adb13d00-961b-11ec-9b84-535b541b2b13.pdf",
    __v: 0,
  },
  {
    _id: "6218b5f0a313cff602ad6e7f",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9747716445,
    secondaryContactNumber: null,
    primaryEmailId: "ssamaslvagese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 4,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [
      {
        skill: "css",
        experience: 5,
        _id: "6218b5f0a313cff602ad6e80",
      },
    ],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\a10e7eb0-9629-11ec-a133-5f73825890eb.docx",
    __v: 0,
  },
  {
    _id: "6218bf662a635f563e39569e",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9747716438,
    secondaryContactNumber: null,
    primaryEmailId: "ssassmaslvagese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 55,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [
      {
        skill: "js",
        experience: 6,
        _id: "6218bf662a635f563e39569f",
      },
    ],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\44a9c9d0-962f-11ec-9f86-3d0af544528c.docx",
    __v: 0,
  },
  {
    _id: "6218c0af9be681045b40502a",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9747226438,
    secondaryContactNumber: null,
    primaryEmailId: "ssassmaslssvagese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 55,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [
      {
        skill: "js",
        experience: 6,
        _id: "6218c0af9be681045b40502b",
      },
    ],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\08fe8fa0-9630-11ec-97b4-e3791a8e98dd.docx",
    __v: 0,
  },
  {
    _id: "6218c14f4884c7b086032384",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9747226444,
    secondaryContactNumber: null,
    primaryEmailId: "ssassmaslssvddagese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 55,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [
      {
        skill: "js",
        experience: 6,
        _id: "6218c14f4884c7b086032385",
      },
    ],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\685e4d50-9630-11ec-a754-5f0d7aad37c3.docx",
    __v: 0,
  },
  {
    _id: "6218c1710a7a4431e749d2f8",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9747226431,
    secondaryContactNumber: null,
    primaryEmailId: "ssassmassvddagese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: " 'wayanad',",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 55,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    currentCompanyName: " 'a',",
    currentDesignation: " 'a',",
    skills: [
      {
        skill: "js",
        experience: 6,
        _id: "6218c1710a7a4431e749d2f9",
      },
    ],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\7cb7a710-9630-11ec-a9a3-9133babf2c6d.docx",
    __v: 0,
  },
  {
    _id: "621c95a7ead056c0b3eddbf7",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9747456431,
    secondaryContactNumber: null,
    primaryEmailId: "sssmassvddagese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: "wayanad",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 55,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    isFresher: "yes\n",
    currentCompanyName: "WebPipl",
    currentDesignation: "Developer",
    skills: [
      {
        skill: "js",
        experience: 6,
        _id: "621c95a7ead056c0b3eddbf8",
      },
    ],
    totalExperience: 4,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\bccc8420-9878-11ec-ae82-d709ea413c74.docx",
    __v: 0,
  },
  {
    _id: "621c98874433d6b1fc592a90",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9747456464,
    secondaryContactNumber: null,
    primaryEmailId: "sssmsvddagese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: "wayanad",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 55,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    isFresher: "yes",
    currentCompanyName: "WebPipl",
    currentDesignation: "Developer",
    skills: [
      {
        skill: "js",
        experience: 6,
        _id: "621c98874433d6b1fc592a91",
      },
    ],
    totalExperience: null,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\736b59d0-987a-11ec-b138-e1affa5d06a2.docx",
    __v: 0,
  },
  {
    _id: "621c99d5c264acb24971daae",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9747456482,
    secondaryContactNumber: null,
    primaryEmailId: "sssmsvddese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: "wayanad",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 55,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    isFresher: "yes",
    currentCompanyName: "WebPipl",
    currentDesignation: "Developer",
    skills: [
      {
        skill: "js",
        experience: 6,
        _id: "621c99d5c264acb24971daaf",
      },
    ],
    totalExperience: null,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\3a816280-987b-11ec-b077-d99836cd45af.docx",
    __v: 0,
  },
  {
    _id: "621c9b6d26a65d8b65ca6aba",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9747451882,
    secondaryContactNumber: null,
    primaryEmailId: "sssmsdese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: "wayanad",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 55,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    isFresher: "yes",
    currentCompanyName: "WebPipl",
    currentDesignation: "Developer",
    skills: [
      {
        skill: "js",
        experience: 6,
        _id: "621c9b6d26a65d8b65ca6abb",
      },
    ],
    totalExperience: 0,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\2de56de0-987c-11ec-9346-9f378dc32829.docx",
    __v: 0,
  },
  {
    _id: "621c9ba461b42bc999f035a8",
    firstName: "thor",
    middleName: "",
    lastName: " 'varghese'",
    dob: "2022-02-21T18:30:00.000Z",
    gender: " 'male'",
    primaryContactNumber: 9927451882,
    secondaryContactNumber: null,
    primaryEmailId: "sssdese593@gmail.com",
    secondaryEmailId: "",
    fatherFirstName: " 'geevarghese',",
    fatherMiddleName: " '',",
    fatherLastName: " 'pm',",
    motherFirstName: " 'jancy',",
    motherMiddleName: " '',",
    motherLastName: " 'varghese',",
    currentLocation: "wayanad",
    preferredLocation: " 'wayanad',",
    currentAddress: " 'wayanad, kerala',",
    permanentAddress: " 'wayanad, kerala',",
    masters: " 'Master of Advanced Study (M.A.S)',",
    mastersSpecialisation: " 'a',",
    mastersYOP: " '2021',",
    mastersPercentage: 100,
    mastersUniName: " 'a',",
    mastersCollegeName: " 'a',",
    graduation: " 'Bachelor of Architecture (BArch)',",
    gradSpecialisation: " 'a',",
    gradYOP: " 'Pursuing',",
    gradPercentage: 2,
    gradUniName: " 'a',",
    gradCollegeName: " 'a',",
    puc: " 'a',",
    pucSpecialisation: " 'a',",
    pucYOP: " 'Pursuing',",
    pucPercentage: 55,
    pucUniName: " 'a',",
    pucSchoolName: " 'a',",
    tenth: " 'a',",
    tenthYOP: " 'Pursuing',",
    tenthPercentage: 3,
    tenthUniName: " 'a',",
    tenthSchoolName: " 'a',",
    isFresher: "yes",
    currentCompanyName: "WebPipl",
    currentDesignation: "Developer",
    skills: [
      {
        skill: "js",
        experience: 6,
        _id: "621c9ba461b42bc999f035a9",
      },
    ],
    totalExperience: 30,
    additionalCourses: " 'a',",
    summary: " 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'",
    resumeFile: "public\\uploads\\4ece43b0-987c-11ec-a1eb-d3dbba7cd743.docx",
    __v: 0,
  },
];
